// Asset manifest. Gameplay code refers to ids only; this table says how each id looks.
//   model          Qt Quick 3D QML produced by balsam from the QtMeshEditor GLB (scripts/import-runtime.py)
//   sprite         sprite sheet rendered from the same GLB by QtMeshEditor (`qtmesh isometric`/`turntable`)
//   representation "model" | "sprite" | "placeholder" - what the game shows for this id right now
//   scale          metres of height for the model (TRELLIS.2 output is a ~1 unit box)
//   footOffset     model units from the origin down to the base (lifts it to y = 0)
//   rotation       yaw degrees so the model faces the camera (+Z)
//   collider       suggested body size in metres (w, h, d) for entities using this asset
//   shadow         { cast, receive }
//   placeholder    what to draw when no model/sprite is available: toon boxes
//   status         "generated" | "pending" | "placeholder"
// A JS module (not JSON): XMLHttpRequest cannot read qrc:/ resources, `import` works everywhere.
// scripts/update-asset-manifest.py fills in model/scale/footOffset/status after an import.
.pragma library

var assets = {
    // ---- characters -------------------------------------------------------------------------
    isabela: { kind: "character", model: "assets/runtime/isabela/Isabela.qml", sprite: null, representation: "model", scale: 1.471, footOffset: 0.51, height: 1.5, unitWidth: 0.8, unitHeight: 1.02, rotation: 180,
               collider: { w: 0.6, h: 1.5, d: 0.5 }, shadow: { cast: true, receive: false }, status: "generated",
               placeholder: { color: "#e64b7a", skin: "#f1c7a8", hair: "#3b2418", w: 0.6, h: 1.5, d: 0.4 },
               clips: { Idle: "Idle", Walk: "Walk", Run: "Run", JumpStart: "Jump", JumpLoop: "Jump", Land: "Land", Push: "Push", Interact: "Pickup",
                        Climb: "Climb", Hang: "Hang", Crawl: "Crouch", Scared: "Hit", Celebrate: "Cheer", Wave: "Wave" } },
    pedro:   { kind: "character", model: "assets/runtime/pedro/Pedro.qml", sprite: null, representation: "model", scale: 1.127, footOffset: 0.51, height: 1.15, unitWidth: 0.9, unitHeight: 1.02, rotation: 180,
               collider: { w: 0.5, h: 1.15, d: 0.45 }, shadow: { cast: true, receive: false }, status: "generated",
               placeholder: { color: "#2f6fd6", skin: "#f1c7a8", hair: "#2a1a10", w: 0.5, h: 1.15, d: 0.35 },
               clips: { Idle: "Idle", Walk: "Walk", Run: "Run", JumpStart: "Jump", JumpLoop: "Jump", Land: "Land", Push: "Push", Interact: "Pickup",
                        Climb: "Climb", Hang: "Hang", Crawl: "Crawl", Scared: "Hit", Celebrate: "Cheer", Wave: "Wave" } },

    // ---- generated from the concept images (QtMeshEditor) -------------------------------------
    school_bench:    { tile: true, sprite: { sheet: "assets/sprites/school_bench.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/school_bench/SchoolBench.qml", representation: "model", scale: 1.724, footOffset: 0.29, height: 1.0, unitWidth: 1.02, unitHeight: 0.58, rotation: 180, collider: { w: 2.4, h: 1.0, d: 0.8 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#8a4b2a", accent: "#2b2b2b", shape: "bench" } },
    school_bin:      { sprite: { sheet: "assets/sprites/school_bin.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/school_bin/SchoolBin.qml", representation: "model", scale: 1.089, footOffset: 0.5, height: 1.1, unitWidth: 0.34, unitHeight: 1.01, rotation: 0, collider: { w: 0.6, h: 1.1, d: 0.6 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#27b3c6", shape: "box", w: 0.6, h: 1.1, d: 0.6 } },
    garden_planter:  { tile: true, sprite: { sheet: "assets/sprites/garden_planter.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/garden_planter/GardenPlanter.qml", representation: "model", scale: 1.194, footOffset: 0.34, height: 0.8, unitWidth: 1.02, unitHeight: 0.67, rotation: 0, collider: { w: 3.0, h: 0.8, d: 1.6 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#5da84a", accent: "#e9e2d0", shape: "planter" } },
    tire_planter:    { tile: true, sprite: { sheet: "assets/sprites/tire_planter.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/tire_planter/TirePlanter.qml", representation: "model", scale: 0.98, footOffset: 0.51, height: 1.0, unitWidth: 0.84, unitHeight: 1.02, rotation: 0, collider: { w: 1.0, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#e33f3f", accent: "#f2c530", shape: "tires" } },
    exercise_bars:   { sprite: { sheet: "assets/sprites/exercise_bars.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/exercise_bars/ExerciseBars.qml", representation: "model", scale: 4.242, footOffset: 0.33, height: 2.8, unitWidth: 1.0, unitHeight: 0.66, rotation: 0, collider: { w: 6.0, h: 2.8, d: 1.5 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#b8422e", shape: "bars" } },
    backpack:        { sprite: { sheet: "assets/sprites/backpack.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/backpack/Backpack.qml", representation: "model", scale: 1.111, footOffset: 0.5, height: 1.122, unitWidth: 0.9, unitHeight: 1.01, rotation: 180, collider: { w: 1.0, h: 1.15, d: 0.7 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#1f4fa3", accent: "#27b3c6", shape: "box", w: 1.0, h: 1.15, d: 0.7 } },
    book_stack:      { tile: true, sprite: { sheet: "assets/sprites/book_stack.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/book_stack/BookStack.qml", representation: "model", scale: 1.351, footOffset: 0.37, height: 1.0, unitWidth: 1.02, unitHeight: 0.74, rotation: 0, collider: { w: 1.4, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#2a5bd7", accent: "#e33f3f", shape: "books" } },
    paper_plane:     { sprite: { sheet: "assets/sprites/paper_plane.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/paper_plane/PaperPlane.qml", representation: "model", scale: 0.938, footOffset: 0.16, height: 0.3, unitWidth: 1.02, unitHeight: 0.32, rotation: 0, collider: { w: 2.0, h: 0.3, d: 1.2 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#f4f4f8", shape: "plane" } },
    playground:      { sprite: { sheet: "assets/sprites/playground.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/playground/Playground.qml", representation: "model", scale: 7.229, footOffset: 0.41, height: 6.0, unitWidth: 1.02, unitHeight: 0.83, rotation: 0, collider: { w: 8.0, h: 6.0, d: 4.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#f2c530", accent: "#e33f3f", shape: "playground" } },
    ramp_and_stairs: { fit: "height", sprite: { sheet: "assets/sprites/ramp_and_stairs.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/ramp_and_stairs/RampAndStairs.qml", representation: "model", scale: 5.128, footOffset: 0.16, height: 1.641, unitWidth: 0.78, unitHeight: 0.32, rotation: 90, collider: { w: 4.0, h: 2.0, d: 3.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#7d8288", accent: "#f2c530", shape: "box", w: 4.0, h: 2.0, d: 3.0 } },
    play_tunnel:     { sprite: { sheet: "assets/sprites/play_tunnel.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/play_tunnel/PlayTunnel.qml", representation: "model", scale: 3.784, footOffset: 0.18, height: 1.4, unitWidth: 1.02, unitHeight: 0.37, rotation: 0, collider: { w: 6.0, h: 1.4, d: 1.4 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#2a5bd7", accent: "#e33f3f", shape: "tunnel" } },
    giant_pencil:    { sprite: { sheet: "assets/sprites/giant_pencil.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/giant_pencil/GiantPencil.qml", representation: "sprite", scale: 3.571, footOffset: 0.14, height: 1.0, unitWidth: 0.28, unitHeight: 0.28, rotation: 0, collider: { w: 4.0, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#f2c530", accent: "#e8a0a0", shape: "pencil" } },
    lunchbox:        { sprite: { sheet: "assets/sprites/lunchbox.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/lunchbox/Lunchbox.qml", representation: "model", scale: 1.02, footOffset: 0.31, height: 0.633, unitWidth: 0.98, unitHeight: 0.62, rotation: 0, collider: { w: 1.0, h: 0.8, d: 0.7 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#27b3c6", accent: "#f2c530", shape: "box", w: 1.0, h: 0.8, d: 0.7 } },
    student_desk:    { sprite: { sheet: "assets/sprites/student_desk.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/student_desk/StudentDesk.qml", representation: "model", scale: 1.429, footOffset: 0.49, height: 1.4, unitWidth: 1.02, unitHeight: 0.98, rotation: 0, collider: { w: 1.6, h: 1.4, d: 1.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#d9a066", accent: "#2a5bd7", shape: "desk" } },
    foosball_table:  { sprite: { sheet: "assets/sprites/foosball_table.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/foosball_table/FoosballTable.qml", representation: "model", scale: 2.83, footOffset: 0.26, height: 1.5, unitWidth: 0.82, unitHeight: 0.53, rotation: 0, collider: { w: 3.0, h: 1.5, d: 1.6 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#c8702e", accent: "#3a9a4a", shape: "table" } },
    ping_pong_table: { sprite: { sheet: "assets/sprites/ping_pong_table.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/ping_pong_table/PingPongTable.qml", representation: "model", scale: 3.137, footOffset: 0.18, height: 1.129, unitWidth: 1.02, unitHeight: 0.36, rotation: 0, collider: { w: 3.2, h: 1.4, d: 1.8 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#2a5bd7", accent: "#2b2b2b", shape: "table" } },
    school_corridor: { sprite: { sheet: "assets/sprites/school_corridor.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "backdrop", model: "assets/runtime/school_corridor/SchoolCorridor.qml", representation: "placeholder", scale: 5880.149, footOffset: 0.26, height: 2998.876, unitWidth: 1.02, unitHeight: 0.51, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "generated", placeholder: { color: "#efe3c6", accent: "#5a4a3a", shape: "corridor" } },
    sports_court:    { sprite: { sheet: "assets/sprites/sports_court.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "backdrop", model: "assets/runtime/sports_court/SportsCourt.qml", representation: "placeholder", scale: 2209.739, footOffset: 0.28, height: 1259.551, unitWidth: 1.02, unitHeight: 0.57, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "generated", placeholder: { color: "#2f6fd6", accent: "#3a9a4a", shape: "court" } },

    // ---- placeholders required by the design brief (no concept image yet) ------------------
    outdoor_tree:    { sprite: { sheet: "assets/sprites/outdoor_tree.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/outdoor_tree/OutdoorTree.qml", representation: "model", scale: 17.51, footOffset: 0.43, height: 15.234, unitWidth: 1.02, unitHeight: 0.87, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#4f9a3c", accent: "#6b4a2b", shape: "tree" } },
    school_gate:     { sprite: { sheet: "assets/sprites/school_gate.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "mechanism", model: "assets/runtime/school_gate/SchoolGate.qml", representation: "model", scale: 2.174, footOffset: 0.51, height: 2.217, unitWidth: 0.46, unitHeight: 1.02, rotation: 0, collider: { w: 1.0, h: 3.6, d: 0.3 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#2a5bd7", accent: "#f2c530", shape: "gate" } },
    school_gate_small: { unitHeight: 1.02, unitWidth: 0.46, fit: "height", kind: "mechanism", model: "assets/runtime/school_gate/SchoolGate.qml", representation: "model", scale: 3.2, footOffset: 0.51, rotation: 0, collider: { w: 0.8, h: 3.2, d: 0.3 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#f2c530", accent: "#2a5bd7", shape: "gate" } },
    colored_grid:    { sprite: { sheet: "assets/sprites/colored_grid.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "mechanism", model: "assets/runtime/colored_grid/ColoredGrid.qml", representation: "model", scale: 1.6, footOffset: 0.51, height: 1.632, unitWidth: 0.5, unitHeight: 1.02, rotation: 0, collider: { w: 0.8, h: 3.4, d: 0.3 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#e33f3f", accent: "#2a5bd7", shape: "gate" } },
    fence:           { kind: "backdrop", model: "", representation: "placeholder", scale: 1.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#3d3d42", shape: "fence" } },
    fence_yellow:    { kind: "prop", model: "", representation: "placeholder", scale: 2.2, footOffset: 0, rotation: 0, collider: { w: 0.5, h: 2.2, d: 0.2 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f2c530", shape: "fence" } },
    fence_yellow_low:{ kind: "prop", model: "", representation: "placeholder", scale: 2.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f2c530", shape: "fence" } },
    school_wall:     { kind: "backdrop", model: "", representation: "placeholder", scale: 4.5, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#f3e7c9", accent: "#e33f3f", shape: "wall" } },
    corridor_wall:   { kind: "prop", model: "", representation: "placeholder", scale: 2.7, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#f3e7c9", shape: "box" } },
    sidewalk:        { kind: "backdrop", model: "", representation: "placeholder", scale: 0.15, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#c9c4b8", shape: "slab" } },
    street:          { kind: "backdrop", model: "", representation: "placeholder", scale: 0.05, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#5b5f66", shape: "slab" } },
    lamp_post:       { sprite: { sheet: "assets/sprites/lamp_post.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "prop", model: "assets/runtime/lamp_post/LampPost.qml", representation: "model", scale: 3.514, footOffset: 0.51, height: 3.584, unitWidth: 0.18, unitHeight: 1.02, rotation: 180, collider: null, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#3d3d42", accent: "#fff2b0", shape: "lamp" } },
    bush:            { sprite: { sheet: "assets/sprites/bush.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/bush/Bush.qml", representation: "model", scale: 1.586, footOffset: 0.48, height: 1.507, unitWidth: 1.0, unitHeight: 0.95, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#3f8a35", shape: "bush" } },
    push_box:        { sprite: { sheet: "assets/sprites/push_box.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "mechanism", model: "assets/runtime/push_box/PushBox.qml", representation: "model", scale: 1.099, footOffset: 0.44, height: 0.967, unitWidth: 0.91, unitHeight: 0.88, rotation: 0, collider: { w: 1.0, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#c98a3e", shape: "box" } },
    floor_button:    { kind: "mechanism", model: "", representation: "placeholder", scale: 0.22, footOffset: 0, rotation: 0, collider: { w: 0.9, h: 0.22, d: 0.9 }, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#e33f3f", accent: "#7d8288", shape: "button" } },
    lever:           { sprite: { sheet: "assets/sprites/lever.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "mechanism", model: "assets/runtime/lever/Lever.qml", representation: "model", scale: 0.633, footOffset: 0.51, height: 0.646, unitWidth: 0.79, unitHeight: 1.02, rotation: 0, collider: { w: 0.5, h: 1.2, d: 0.3 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#7d8288", accent: "#e33f3f", shape: "lever" } },
    plate:           { kind: "mechanism", model: "", representation: "placeholder", scale: 0.12, footOffset: 0, rotation: 0, collider: { w: 1.2, h: 0.12, d: 1.0 }, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#f2c530", accent: "#2a5bd7", shape: "plate" } },
    moving_platform: { sprite: { sheet: "assets/sprites/moving_platform.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "width", kind: "mechanism", model: "assets/runtime/moving_platform/MovingPlatform.qml", representation: "model", scale: 0.795, footOffset: 0.2, height: 0.35, unitWidth: 1.02, unitHeight: 0.44, rotation: 0, collider: { w: 2.2, h: 0.35, d: 1.2 }, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#b8422e", accent: "#f2c530", shape: "swing" } },
    parallel_bars:   { fit: "height", sprite: { sheet: "assets/sprites/parallel_bars.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/parallel_bars/ParallelBars.qml", representation: "model", scale: 8.966, footOffset: 0.14, height: 2.6, unitWidth: 0.19, unitHeight: 0.29, rotation: 90, collider: { w: 8.0, h: 2.6, d: 1.2 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#b8422e", shape: "bars" } },
    parallel_bars_top:{ kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#b8422e", shape: "beam" } },
    exercise_bar:    { kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#b8422e", shape: "beam" } },
    climbing_ladder: { sprite: { sheet: "assets/sprites/climbing_ladder.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "prop", model: "assets/runtime/climbing_ladder/ClimbingLadder.qml", representation: "model", scale: 2.511, footOffset: 0.51, height: 2.561, unitWidth: 0.58, unitHeight: 1.02, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#7d8288", accent: "#f2c530", shape: "ladder" } },
    playground_deck: { kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#f2c530", accent: "#e33f3f", shape: "deck" } },
    playground_roof: { kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#2a5bd7", shape: "deck" } },
    narrow_beam:     { kind: "prop", model: "", representation: "placeholder", scale: 0.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#e33f3f", shape: "beam" } },
    slide_step:      { kind: "prop", model: "", representation: "placeholder", scale: 0.6, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#f07a2a", shape: "box" } },
    stair_step:      { kind: "prop", model: "", representation: "placeholder", scale: 0.5, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#7d8288", accent: "#f2c530", shape: "box" } },
    soccer_ball:     { sprite: { sheet: "assets/sprites/soccer_ball.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/soccer_ball/SoccerBall.qml", representation: "model", scale: 0.882, footOffset: 0.51, height: 0.9, unitWidth: 1.02, unitHeight: 1.02, rotation: 0, collider: { w: 0.9, h: 0.9, d: 0.9 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#f4f4f8", accent: "#2b2b2b", shape: "ball" } },
    goal:            { sprite: { sheet: "assets/sprites/goal.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/goal/Goal.qml", representation: "model", scale: 24.47, footOffset: 0.37, height: 18.108, unitWidth: 1.02, unitHeight: 0.74, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#f4f4f8", shape: "goal" } },
    basket_hoop:     { sprite: { sheet: "assets/sprites/basket_hoop.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/basket_hoop/BasketHoop.qml", representation: "model", scale: 3.012, footOffset: 0.51, height: 3.072, unitWidth: 0.44, unitHeight: 1.02, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#f07a2a", accent: "#f4f4f8", shape: "hoop" } },
    bleachers:       { sprite: { sheet: "assets/sprites/bleachers.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", tile: true, kind: "prop", model: "assets/runtime/bleachers/Bleachers.qml", representation: "model", scale: 1734.92, footOffset: 0.23, height: 798.063, unitWidth: 0.47, unitHeight: 0.46, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#2a5bd7", accent: "#f2c530", shape: "bleachers" } },
    bleachers_top:   { kind: "prop", model: "", representation: "placeholder", scale: 0.4, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#2a5bd7", shape: "deck" } },
    court_roof:      { kind: "backdrop", model: "", representation: "placeholder", scale: 7.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#7d8288", shape: "roof" } },
    stone_platform:  { sprite: { sheet: "assets/sprites/stone_platform.png", columns: 8, rows: 1, frames: 8, fps: 0 }, tile: true, kind: "prop", model: "assets/runtime/stone_platform/StonePlatform.qml", representation: "model", scale: 555209.583, footOffset: 0.12, height: 127698.204, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "generated", placeholder: { color: "#9a9187", accent: "#6cc04a", shape: "block" }, unitWidth: 1.01, unitHeight: 0.23 },
    window_ledge:    { kind: "prop", model: "", representation: "placeholder", scale: 0.4, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#dfe7ef", accent: "#9fb7c9", shape: "window" } },
    student_desk_row:{ tile: true, kind: "prop", model: "", representation: "placeholder", scale: 2.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#d9a066", accent: "#2a5bd7", shape: "deskrow" } },
    student_desk_top:{ kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#d9a066", shape: "deck" } },
    school_clock:    { sprite: { sheet: "assets/sprites/school_clock.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "prop", model: "assets/runtime/school_clock/SchoolClock.qml", representation: "model", scale: 1.196, footOffset: 0.5, height: 1.208, unitWidth: 0.98, unitHeight: 1.01, rotation: 180, collider: null, shadow: { cast: false, receive: false }, status: "generated", placeholder: { color: "#f4f4f8", accent: "#2b2b2b", shape: "clock" } },
    final_door:      { sprite: { sheet: "assets/sprites/final_door.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "mechanism", model: "assets/runtime/final_door/FinalDoor.qml", representation: "model", scale: 2.667, footOffset: 0.51, height: 2.72, unitWidth: 0.6, unitHeight: 1.02, rotation: 0, collider: { w: 1.6, h: 3.0, d: 0.3 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#8a4b2a", accent: "#f2c530", shape: "door" } },
    star:            { sprite: { sheet: "assets/sprites/star.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "collectible", model: "assets/runtime/star/Star.qml", representation: "model", scale: 0.714, footOffset: 0.49, height: 0.7, unitWidth: 0.46, unitHeight: 0.98, rotation: 90, collider: { w: 0.7, h: 0.7, d: 0.7 }, shadow: { cast: false, receive: false }, status: "generated", placeholder: { color: "#ffd23f", shape: "star" } },
    pencil_collectible:{ sprite: { sheet: "assets/sprites/pencil_collectible.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "collectible", model: "assets/runtime/pencil_collectible/PencilCollectible.qml", representation: "model", scale: 0.882, footOffset: 0.51, height: 0.9, unitWidth: 0.4, unitHeight: 1.02, rotation: 0, collider: { w: 0.7, h: 0.9, d: 0.7 }, shadow: { cast: false, receive: false }, status: "generated", placeholder: { color: "#e33f3f", accent: "#f2c530", shape: "pencil" } },
    memory:          { sprite: { sheet: "assets/sprites/memory.png", columns: 8, rows: 1, frames: 8, fps: 0 }, kind: "collectible", model: "assets/runtime/memory/Memory.qml", representation: "model", scale: 0.784, footOffset: 0.51, height: 0.8, unitWidth: 0.74, unitHeight: 1.02, rotation: 180, collider: { w: 0.8, h: 0.8, d: 0.6 }, shadow: { cast: false, receive: false }, status: "generated", placeholder: { color: "#f4f4f8", accent: "#e64b7a", shape: "photo" } },
    checkpoint_marker:{ sprite: { sheet: "assets/sprites/checkpoint_marker.png", columns: 8, rows: 1, frames: 8, fps: 0 }, fit: "height", kind: "mechanism", model: "assets/runtime/checkpoint_marker/CheckpointMarker.qml", representation: "model", scale: 0.58, footOffset: 0.51, height: 0.591, unitWidth: 0.69, unitHeight: 1.02, rotation: 0, collider: { w: 0.4, h: 2.2, d: 0.4 }, shadow: { cast: true, receive: false }, status: "generated", placeholder: { color: "#3a9a4a", accent: "#ffd23f", shape: "flag" } }
}

function get(id) { return assets[id] || null }
function ids() { return Object.keys(assets) }
function generated() { return Object.keys(assets).filter(function (k) { return assets[k].status === "generated" }) }
