// Asset manifest. Gameplay code refers to ids only; this table says how each id looks.
//   model          Qt Quick 3D QML produced by balsam from the QtMeshEditor GLB (scripts/import-runtime.py)
//   sprite         sprite sheet rendered from the same GLB by QtMeshEditor (`qtmesh isometric`/`turntable`)
//   representation "model" | "sprite" | "placeholder" - what the game shows for this id right now
//   scale          metres of height for the model (TRELLIS.2 output is a ~1 unit box)
//   footOffset     model units from the origin down to the base (lifts it to y = 0)
//   rotation       yaw degrees so the model faces the camera (+Z)
//   collider       suggested body size in metres (w, h, d) for entities using this asset
//   shadow         { cast, receive }
//   placeholder    what to draw when no model/sprite is available: toon boxes
//   status         "generated" | "pending" | "placeholder"
// A JS module (not JSON): XMLHttpRequest cannot read qrc:/ resources, `import` works everywhere.
// scripts/update-asset-manifest.py fills in model/scale/footOffset/status after an import.
.pragma library

var assets = {
    // ---- characters -------------------------------------------------------------------------
    isabela: { kind: "character", model: "assets/runtime/isabela/Isabela.qml", sprite: null, representation: "model", scale: 1.5, footOffset: 0.51, unitHeight: 1.02, rotation: 0,
               collider: { w: 0.6, h: 1.5, d: 0.5 }, shadow: { cast: true, receive: false }, status: "generated",
               placeholder: { color: "#e64b7a", skin: "#f1c7a8", hair: "#3b2418", w: 0.6, h: 1.5, d: 0.4 },
               clips: { Idle: "Idle", Walk: "Walk", Run: "Run", JumpStart: "Jump", JumpLoop: "Jump", Land: "Land", Push: "Push", Interact: "Pickup",
                        Climb: "Climb", Hang: "Hang", Crawl: "Crouch", Scared: "Hit", Celebrate: "Cheer", Wave: "Wave" } },
    pedro:   { kind: "character", model: "assets/runtime/pedro/Pedro.qml", sprite: null, representation: "model", scale: 1.15, footOffset: 0.51, unitHeight: 1.02, rotation: 0,
               collider: { w: 0.5, h: 1.15, d: 0.45 }, shadow: { cast: true, receive: false }, status: "generated",
               placeholder: { color: "#2f6fd6", skin: "#f1c7a8", hair: "#2a1a10", w: 0.5, h: 1.15, d: 0.35 },
               clips: { Idle: "Idle", Walk: "Walk", Run: "Run", JumpStart: "Jump", JumpLoop: "Jump", Land: "Land", Push: "Push", Interact: "Pickup",
                        Climb: "Climb", Hang: "Hang", Crawl: "Crawl", Scared: "Hit", Celebrate: "Cheer", Wave: "Wave" } },

    // ---- generated from the concept images (QtMeshEditor) -------------------------------------
    school_bench:    { kind: "prop", model: "", representation: "placeholder", scale: 1.0, footOffset: 0.5, rotation: 0, collider: { w: 2.4, h: 1.0, d: 0.8 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#8a4b2a", accent: "#2b2b2b", shape: "bench" } },
    school_bin:      { kind: "prop", model: "", representation: "placeholder", scale: 1.1, footOffset: 0.5, rotation: 0, collider: { w: 0.6, h: 1.1, d: 0.6 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#27b3c6", shape: "box", w: 0.6, h: 1.1, d: 0.6 } },
    garden_planter:  { kind: "prop", model: "", representation: "placeholder", scale: 0.9, footOffset: 0.5, rotation: 0, collider: { w: 3.0, h: 0.8, d: 1.6 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#5da84a", accent: "#e9e2d0", shape: "planter" } },
    tire_planter:    { kind: "prop", model: "", representation: "placeholder", scale: 1.0, footOffset: 0.5, rotation: 0, collider: { w: 1.0, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#e33f3f", accent: "#f2c530", shape: "tires" } },
    exercise_bars:   { kind: "prop", model: "", representation: "placeholder", scale: 2.8, footOffset: 0.5, rotation: 0, collider: { w: 6.0, h: 2.8, d: 1.5 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#b8422e", shape: "bars" } },
    backpack:        { kind: "prop", model: "", representation: "placeholder", scale: 1.15, footOffset: 0.5, rotation: 0, collider: { w: 1.0, h: 1.15, d: 0.7 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#1f4fa3", accent: "#27b3c6", shape: "box", w: 1.0, h: 1.15, d: 0.7 } },
    book_stack:      { kind: "prop", model: "", representation: "placeholder", scale: 1.0, footOffset: 0.5, rotation: 0, collider: { w: 1.4, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#2a5bd7", accent: "#e33f3f", shape: "books" } },
    paper_plane:     { kind: "prop", model: "", representation: "placeholder", scale: 0.5, footOffset: 0.5, rotation: 0, collider: { w: 2.0, h: 0.3, d: 1.2 }, shadow: { cast: true, receive: false }, status: "pending", placeholder: { color: "#f4f4f8", shape: "plane" } },
    playground:      { kind: "prop", model: "", representation: "placeholder", scale: 6.0, footOffset: 0.5, rotation: 0, collider: { w: 8.0, h: 6.0, d: 4.0 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#f2c530", accent: "#e33f3f", shape: "playground" } },
    ramp_and_stairs: { kind: "prop", model: "", representation: "placeholder", scale: 2.0, footOffset: 0.5, rotation: 0, collider: { w: 4.0, h: 2.0, d: 3.0 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#7d8288", accent: "#f2c530", shape: "box", w: 4.0, h: 2.0, d: 3.0 } },
    play_tunnel:     { kind: "prop", model: "", representation: "placeholder", scale: 1.4, footOffset: 0.5, rotation: 0, collider: { w: 6.0, h: 1.4, d: 1.4 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#2a5bd7", accent: "#e33f3f", shape: "tunnel" } },
    giant_pencil:    { kind: "prop", model: "", representation: "placeholder", scale: 1.6, footOffset: 0.5, rotation: 0, collider: { w: 4.0, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#f2c530", accent: "#e8a0a0", shape: "pencil" } },
    lunchbox:        { kind: "prop", model: "", representation: "placeholder", scale: 0.8, footOffset: 0.5, rotation: 0, collider: { w: 1.0, h: 0.8, d: 0.7 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#27b3c6", accent: "#f2c530", shape: "box", w: 1.0, h: 0.8, d: 0.7 } },
    student_desk:    { kind: "prop", model: "", representation: "placeholder", scale: 1.4, footOffset: 0.5, rotation: 0, collider: { w: 1.6, h: 1.4, d: 1.0 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#d9a066", accent: "#2a5bd7", shape: "desk" } },
    foosball_table:  { kind: "prop", model: "", representation: "placeholder", scale: 1.5, footOffset: 0.5, rotation: 0, collider: { w: 3.0, h: 1.5, d: 1.6 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#c8702e", accent: "#3a9a4a", shape: "table" } },
    ping_pong_table: { kind: "prop", model: "", representation: "placeholder", scale: 1.4, footOffset: 0.5, rotation: 0, collider: { w: 3.2, h: 1.4, d: 1.8 }, shadow: { cast: true, receive: true }, status: "pending", placeholder: { color: "#2a5bd7", accent: "#2b2b2b", shape: "table" } },
    school_corridor: { kind: "backdrop", model: "", representation: "placeholder", scale: 7.0, footOffset: 0.5, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "pending", placeholder: { color: "#efe3c6", accent: "#5a4a3a", shape: "corridor" } },
    sports_court:    { kind: "backdrop", model: "", representation: "placeholder", scale: 8.0, footOffset: 0.5, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "pending", placeholder: { color: "#2f6fd6", accent: "#3a9a4a", shape: "court" } },

    // ---- placeholders required by the design brief (no concept image yet) ------------------
    outdoor_tree:    { kind: "prop", model: "", representation: "placeholder", scale: 5.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#4f9a3c", accent: "#6b4a2b", shape: "tree" } },
    school_gate:     { kind: "mechanism", model: "", representation: "placeholder", scale: 3.6, footOffset: 0, rotation: 0, collider: { w: 1.0, h: 3.6, d: 0.3 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#2a5bd7", accent: "#f2c530", shape: "gate" } },
    school_gate_small: { kind: "mechanism", model: "", representation: "placeholder", scale: 3.2, footOffset: 0, rotation: 0, collider: { w: 0.8, h: 3.2, d: 0.3 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f2c530", accent: "#2a5bd7", shape: "gate" } },
    colored_grid:    { kind: "mechanism", model: "", representation: "placeholder", scale: 3.4, footOffset: 0, rotation: 0, collider: { w: 0.8, h: 3.4, d: 0.3 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#e33f3f", accent: "#2a5bd7", shape: "gate" } },
    fence:           { kind: "backdrop", model: "", representation: "placeholder", scale: 1.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#3d3d42", shape: "fence" } },
    fence_yellow:    { kind: "prop", model: "", representation: "placeholder", scale: 2.2, footOffset: 0, rotation: 0, collider: { w: 0.5, h: 2.2, d: 0.2 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f2c530", shape: "fence" } },
    fence_yellow_low:{ kind: "prop", model: "", representation: "placeholder", scale: 2.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f2c530", shape: "fence" } },
    school_wall:     { kind: "backdrop", model: "", representation: "placeholder", scale: 4.5, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#f3e7c9", accent: "#e33f3f", shape: "wall" } },
    corridor_wall:   { kind: "prop", model: "", representation: "placeholder", scale: 2.7, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#f3e7c9", shape: "box" } },
    sidewalk:        { kind: "backdrop", model: "", representation: "placeholder", scale: 0.15, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#c9c4b8", shape: "slab" } },
    street:          { kind: "backdrop", model: "", representation: "placeholder", scale: 0.05, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#5b5f66", shape: "slab" } },
    lamp_post:       { kind: "backdrop", model: "", representation: "placeholder", scale: 4.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#3d3d42", accent: "#fff2b0", shape: "lamp" } },
    bush:            { kind: "backdrop", model: "", representation: "placeholder", scale: 1.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#3f8a35", shape: "bush" } },
    push_box:        { kind: "mechanism", model: "", representation: "placeholder", scale: 1.0, footOffset: 0, rotation: 0, collider: { w: 1.0, h: 1.0, d: 1.0 }, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#c98a3e", shape: "box" } },
    floor_button:    { kind: "mechanism", model: "", representation: "placeholder", scale: 0.22, footOffset: 0, rotation: 0, collider: { w: 0.9, h: 0.22, d: 0.9 }, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#e33f3f", accent: "#7d8288", shape: "button" } },
    lever:           { kind: "mechanism", model: "", representation: "placeholder", scale: 1.2, footOffset: 0, rotation: 0, collider: { w: 0.5, h: 1.2, d: 0.3 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#7d8288", accent: "#e33f3f", shape: "lever" } },
    plate:           { kind: "mechanism", model: "", representation: "placeholder", scale: 0.12, footOffset: 0, rotation: 0, collider: { w: 1.2, h: 0.12, d: 1.0 }, shadow: { cast: false, receive: true }, status: "placeholder", placeholder: { color: "#f2c530", accent: "#2a5bd7", shape: "plate" } },
    moving_platform: { kind: "mechanism", model: "", representation: "placeholder", scale: 0.35, footOffset: 0, rotation: 0, collider: { w: 2.2, h: 0.35, d: 1.2 }, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#b8422e", accent: "#f2c530", shape: "swing" } },
    parallel_bars:   { kind: "prop", model: "", representation: "placeholder", scale: 2.6, footOffset: 0, rotation: 0, collider: { w: 8.0, h: 2.6, d: 1.2 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#b8422e", shape: "bars" } },
    parallel_bars_top:{ kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#b8422e", shape: "beam" } },
    exercise_bar:    { kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#b8422e", shape: "beam" } },
    climbing_ladder: { kind: "prop", model: "", representation: "placeholder", scale: 3.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#7d8288", accent: "#f2c530", shape: "ladder" } },
    playground_deck: { kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#f2c530", accent: "#e33f3f", shape: "deck" } },
    playground_roof: { kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#2a5bd7", shape: "deck" } },
    narrow_beam:     { kind: "prop", model: "", representation: "placeholder", scale: 0.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#e33f3f", shape: "beam" } },
    slide_step:      { kind: "prop", model: "", representation: "placeholder", scale: 0.6, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#f07a2a", shape: "box" } },
    stair_step:      { kind: "prop", model: "", representation: "placeholder", scale: 0.5, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#7d8288", accent: "#f2c530", shape: "box" } },
    soccer_ball:     { kind: "prop", model: "", representation: "placeholder", scale: 0.9, footOffset: 0, rotation: 0, collider: { w: 0.9, h: 0.9, d: 0.9 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f4f4f8", accent: "#2b2b2b", shape: "ball" } },
    goal:            { kind: "prop", model: "", representation: "placeholder", scale: 2.2, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f4f4f8", shape: "goal" } },
    basket_hoop:     { kind: "backdrop", model: "", representation: "placeholder", scale: 3.6, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#f07a2a", accent: "#f4f4f8", shape: "hoop" } },
    bleachers:       { kind: "prop", model: "", representation: "placeholder", scale: 1.6, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#2a5bd7", accent: "#f2c530", shape: "bleachers" } },
    bleachers_top:   { kind: "prop", model: "", representation: "placeholder", scale: 0.4, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#2a5bd7", shape: "deck" } },
    court_roof:      { kind: "backdrop", model: "", representation: "placeholder", scale: 7.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#7d8288", shape: "roof" } },
    window_ledge:    { kind: "prop", model: "", representation: "placeholder", scale: 0.4, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#dfe7ef", accent: "#9fb7c9", shape: "window" } },
    student_desk_row:{ kind: "prop", model: "", representation: "placeholder", scale: 2.0, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#d9a066", accent: "#2a5bd7", shape: "deskrow" } },
    student_desk_top:{ kind: "prop", model: "", representation: "placeholder", scale: 0.3, footOffset: 0, rotation: 0, collider: null, shadow: { cast: true, receive: true }, status: "placeholder", placeholder: { color: "#d9a066", shape: "deck" } },
    school_clock:    { kind: "backdrop", model: "", representation: "placeholder", scale: 1.4, footOffset: 0, rotation: 0, collider: null, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#f4f4f8", accent: "#2b2b2b", shape: "clock" } },
    final_door:      { kind: "mechanism", model: "", representation: "placeholder", scale: 3.0, footOffset: 0, rotation: 0, collider: { w: 1.6, h: 3.0, d: 0.3 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#8a4b2a", accent: "#f2c530", shape: "door" } },
    star:            { kind: "collectible", model: "", representation: "placeholder", scale: 0.5, footOffset: 0, rotation: 0, collider: { w: 0.7, h: 0.7, d: 0.7 }, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#ffd23f", shape: "star" } },
    pencil_collectible:{ kind: "collectible", model: "", representation: "placeholder", scale: 0.8, footOffset: 0, rotation: 0, collider: { w: 0.7, h: 0.9, d: 0.7 }, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#e33f3f", accent: "#f2c530", shape: "pencil" } },
    memory:          { kind: "collectible", model: "", representation: "placeholder", scale: 0.8, footOffset: 0, rotation: 0, collider: { w: 0.8, h: 0.8, d: 0.6 }, shadow: { cast: false, receive: false }, status: "placeholder", placeholder: { color: "#f4f4f8", accent: "#e64b7a", shape: "photo" } },
    checkpoint_marker:{ kind: "mechanism", model: "", representation: "placeholder", scale: 2.2, footOffset: 0, rotation: 0, collider: { w: 0.4, h: 2.2, d: 0.4 }, shadow: { cast: true, receive: false }, status: "placeholder", placeholder: { color: "#3a9a4a", accent: "#ffd23f", shape: "flag" } }
}

function get(id) { return assets[id] || null }
function ids() { return Object.keys(assets) }
function generated() { return Object.keys(assets).filter(function (k) { return assets[k].status === "generated" }) }
