// UI strings. Brazilian Portuguese is the shipped language; every key also has an English
// entry so the game can be switched (Settings) and so missing translations are caught by tests.
.pragma library

var pt_BR = {
    "game.title": "Isabela & Pedro",
    "game.subtitle": "A Escola Virou Aventura",
    "game.school": "Escola Horizonte",
    "level.caminho.name": "O Caminho para a Sala",
    "section.pracinha": "A pracinha",
    "section.jardim": "O jardim",
    "section.playground": "O playground",
    "section.patio": "O pátio de jogos",
    "section.quadra": "A quadra coberta",
    "section.corredor": "O corredor gigante",

    "menu.newGame": "Novo jogo",
    "menu.continue": "Continuar",
    "menu.controls": "Controles",
    "menu.volume": "Volume",
    "menu.music": "Música",
    "menu.effects": "Efeitos",
    "menu.language": "Idioma",
    "menu.resume": "Voltar ao jogo",
    "menu.restartCheckpoint": "Reiniciar no checkpoint",
    "menu.quitToTitle": "Voltar ao menu",
    "menu.paused": "Pausa",
    "menu.back": "Voltar",
    "menu.gallery": "Galeria",
    "menu.loading": "Carregando a imaginação...",
    "menu.pressStart": "Pressione Espaço ou Start",
    "menu.nextLevel": "Próxima fase: Em breve",
    "menu.playAgain": "Jogar de novo",
    "menu.confirmNew": "Começar um novo jogo apaga o progresso salvo. Continuar?",
    "menu.yes": "Sim",
    "menu.no": "Não",

    "controls.title": "Controles",
    "controls.move": "Mover",
    "controls.jump": "Pular (segure para pular mais alto)",
    "controls.interact": "Interagir",
    "controls.switch": "Trocar de personagem",
    "controls.ability": "Habilidade especial",
    "controls.crouch": "Abaixar / passar por baixo (Pedro)",
    "controls.pause": "Pausar",
    "controls.keyboard": "Teclado",
    "controls.gamepad": "Controle",
    "controls.gamepadNote": "Controles (gamepad) funcionam no navegador; no computador use o teclado.",

    "hud.courage": "Coragem",
    "hud.stars": "Estrelas",
    "hud.pencils": "Lápis",
    "hud.interact": "Interagir",
    "hud.needBoth": "Os dois irmãos precisam estar aqui",
    "hud.checkpoint": "Checkpoint!",
    "hud.courageLost": "Ops! Coragem -1",
    "hud.courageOut": "Respira fundo... de volta ao checkpoint",
    "hud.memoryFound": "Memória da Família encontrada!",
    "hud.pencilFound": "Lápis colorido!",
    "hud.gateOpen": "O portão se abriu!",
    "hud.mechanism": "Mecanismo ativado",
    "hud.revealed": "O caderno da Isabela revelou um caminho!",
    "hud.curiosity": "A curiosidade do Pedro encontrou algo!",
    "hud.nothingHere": "Nada por aqui... ainda.",
    "hud.pushTooHeavy": "Pesado demais para o Pedro. Chame a Isabela!",
    "hud.tooHigh": "Alto demais para o Pedro. A Isabela alcança!",
    "hud.tooSmall": "Só o Pedro passa por aqui!",

    "hint.move": "Use as SETAS ou A/D para andar. Continue andando para correr!",
    "hint.jump": "Pressione ESPAÇO para pular. Segure para pular mais alto.",
    "hint.stars": "Colete as Estrelas de Coragem!",
    "hint.switch": "Pressione Q ou TAB para trocar entre Isabela e Pedro.",
    "hint.abilities": "Isabela pula alto e se agarra em bordas. Pedro é rápido e passa por baixo.",
    "hint.crawl": "Com o Pedro, segure ↓ para se abaixar e passar por baixo.",
    "hint.ledge": "Com a Isabela, pule em direção a uma borda para se agarrar. ↑ para subir.",
    "hint.button": "Pise no botão para ativá-lo.",
    "hint.lever": "Pressione E perto da alavanca.",
    "hint.push": "Ande contra a caixa para empurrá-la.",
    "hint.pushmedium": "O banco é pesado: só a Isabela consegue empurrar.",
    "hint.moving": "Observe o ritmo da plataforma antes de pular.",
    "hint.plates": "Isabela e Pedro precisam ficar juntos sobre as marcas.",
    "hint.notebook": "Com a Isabela, pressione SHIFT para usar o caderno e revelar pistas.",
    "hint.notebook2": "Parece que falta um caminho aqui... O caderno da Isabela pode ajudar.",
    "hint.playground": "O playground ficou enorme! Isabela sobe; Pedro atravessa o túnel.",
    "hint.patio": "Salte entre os bancos e as mesas.",
    "hint.ball": "Cuidado com a bola! Ela só assusta, mas custa Coragem.",
    "hint.pushbutton": "Empurre a lancheira até o botão.",
    "hint.quadra": "Leve a bola até o gol. Pedro passa por baixo da arquibancada.",
    "hint.corridor": "O corredor cresceu! Pule sobre os livros e cuidado com os aviões.",
    "hint.desk": "Empurre a carteira até a janela para alcançar a beirada.",

    "story.bell": "🔔 O sinal tocou! A imaginação dos irmãos transforma o caminho em aventura...",
    "story.gate_far": "O portão parece cada vez mais distante...",
    "story.gate_open": "Juntos, Isabela e Pedro abrem o portão da Escola Horizonte!",
    "story.corridor_grows": "O corredor cresce como um labirinto. O relógio marca a hora!",
    "story.finished": "Chegaram! O mundo volta ao normal e os irmãos comemoram.",
    "story.intro": "Isabela e Pedro esperam na pracinha em frente à escola.",

    "end.title": "Fase concluída!",
    "end.stars": "Estrelas de Coragem",
    "end.pencils": "Lápis coloridos",
    "end.memory": "Memória da Família",
    "end.found": "encontrada",
    "end.notFound": "ainda escondida",
    "end.time": "Tempo",
    "end.best": "Melhor tempo",

    "gallery.title": "Galeria",
    "gallery.locked": "Encontre a Memória da Família na pracinha para desbloquear.",
    "gallery.memory1.title": "Um dia na pracinha",
    "gallery.memory1.text": "Um desenho da família toda sentada no banco da praça, com sorvete e um avião de papel.",

    "char.isabela": "Isabela",
    "char.pedro": "Pedro",
    "dev.title": "Ferramentas de desenvolvimento"
}

var en = {
    "game.title": "Isabela & Pedro",
    "game.subtitle": "School Turned Adventure",
    "game.school": "Horizonte School",
    "level.caminho.name": "The Way to the Classroom",
    "section.pracinha": "The square",
    "section.jardim": "The garden",
    "section.playground": "The playground",
    "section.patio": "The games yard",
    "section.quadra": "The covered court",
    "section.corredor": "The giant corridor",
    "menu.newGame": "New game", "menu.continue": "Continue", "menu.controls": "Controls", "menu.volume": "Volume",
    "menu.music": "Music", "menu.effects": "Effects", "menu.language": "Language", "menu.resume": "Resume",
    "menu.restartCheckpoint": "Restart at checkpoint", "menu.quitToTitle": "Back to title", "menu.paused": "Paused",
    "menu.back": "Back", "menu.gallery": "Gallery", "menu.loading": "Loading imagination...",
    "menu.pressStart": "Press Space or Start", "menu.nextLevel": "Next level: Coming soon", "menu.playAgain": "Play again",
    "menu.confirmNew": "Starting a new game erases the saved progress. Continue?", "menu.yes": "Yes", "menu.no": "No",
    "controls.title": "Controls", "controls.move": "Move", "controls.jump": "Jump (hold for a higher jump)",
    "controls.interact": "Interact", "controls.switch": "Switch character", "controls.ability": "Special ability",
    "controls.crouch": "Crouch / crawl under (Pedro)", "controls.pause": "Pause", "controls.keyboard": "Keyboard",
    "controls.gamepad": "Gamepad", "controls.gamepadNote": "Gamepads work in the browser; on desktop use the keyboard.",
    "hud.courage": "Courage", "hud.stars": "Stars", "hud.pencils": "Pencils", "hud.interact": "Interact",
    "hud.needBoth": "Both siblings need to be here", "hud.checkpoint": "Checkpoint!", "hud.courageLost": "Oops! Courage -1",
    "hud.courageOut": "Deep breath... back to the checkpoint", "hud.memoryFound": "Family Memory found!",
    "hud.pencilFound": "Coloured pencil!", "hud.gateOpen": "The gate opened!", "hud.mechanism": "Mechanism activated",
    "hud.revealed": "Isabela's notebook revealed a path!", "hud.curiosity": "Pedro's curiosity found something!",
    "hud.nothingHere": "Nothing here... yet.", "hud.pushTooHeavy": "Too heavy for Pedro. Call Isabela!",
    "hud.tooHigh": "Too high for Pedro. Isabela can reach it!", "hud.tooSmall": "Only Pedro fits through here!",
    "hint.move": "Use the ARROWS or A/D to walk. Keep walking to run!",
    "hint.jump": "Press SPACE to jump. Hold it to jump higher.",
    "hint.stars": "Collect the Courage Stars!",
    "hint.switch": "Press Q or TAB to switch between Isabela and Pedro.",
    "hint.abilities": "Isabela jumps high and grabs ledges. Pedro is fast and crawls under things.",
    "hint.crawl": "As Pedro, hold ↓ to crouch and crawl under.",
    "hint.ledge": "As Isabela, jump towards a ledge to grab it. ↑ to climb.",
    "hint.button": "Step on the button to activate it.",
    "hint.lever": "Press E next to the lever.",
    "hint.push": "Walk into the box to push it.",
    "hint.pushmedium": "The bench is heavy: only Isabela can push it.",
    "hint.moving": "Watch the platform's rhythm before jumping.",
    "hint.plates": "Isabela and Pedro must stand together on the marks.",
    "hint.notebook": "As Isabela, press SHIFT to use the notebook and reveal clues.",
    "hint.notebook2": "A path seems to be missing here... Isabela's notebook may help.",
    "hint.playground": "The playground is huge! Isabela climbs; Pedro goes through the tunnel.",
    "hint.patio": "Hop between the benches and tables.",
    "hint.ball": "Watch the ball! It only startles, but it costs Courage.",
    "hint.pushbutton": "Push the lunchbox onto the button.",
    "hint.quadra": "Take the ball to the goal. Pedro fits under the stands.",
    "hint.corridor": "The corridor grew! Jump over the books and mind the planes.",
    "hint.desk": "Push the desk to the window to reach the ledge.",
    "story.bell": "🔔 The bell rang! The siblings' imagination turns the way into an adventure...",
    "story.gate_far": "The gate seems farther and farther away...",
    "story.gate_open": "Together, Isabela and Pedro open the gate of Horizonte School!",
    "story.corridor_grows": "The corridor grows like a maze. The clock is ticking!",
    "story.finished": "They made it! The world goes back to normal and the siblings celebrate.",
    "story.intro": "Isabela and Pedro wait in the square in front of the school.",
    "end.title": "Level complete!", "end.stars": "Courage Stars", "end.pencils": "Coloured pencils", "end.memory": "Family Memory",
    "end.found": "found", "end.notFound": "still hidden", "end.time": "Time", "end.best": "Best time",
    "gallery.title": "Gallery", "gallery.locked": "Find the Family Memory in the square to unlock.",
    "gallery.memory1.title": "A day in the square",
    "gallery.memory1.text": "A drawing of the whole family on the park bench, with ice cream and a paper plane.",
    "char.isabela": "Isabela", "char.pedro": "Pedro", "dev.title": "Development tools"
}

var languages = { pt_BR: pt_BR, en: en }

function tr(key, lang) {
    const table = languages[lang || "pt_BR"] || pt_BR
    if (table[key] !== undefined) return table[key]
    if (pt_BR[key] !== undefined) return pt_BR[key]
    return key
}
